2019-10-30-main-ERROR-com.cg.BankingSystem.dao.AdminDaoImpl:InvalidCredentialsException thrown is AdminDao.authenticateUser() method with cause: Invalid Credentials! Please enter valid credentials.
2019-10-30-main-INFO -com.cg.BankingSystem.dao.AdminDaoImpl:Admin logged in successfully at: 2019-10-30T16:49:59.260
2019-10-30-main-INFO -com.cg.BankingSystem.dao.AdminDaoImpl:Create new account method initiated in DAO Layer.
2019-10-30-main-INFO -com.cg.BankingSystem.dao.AdminDaoImpl:AdminDao.createNewAccount(): New account added to account_master table for creating new account.
2019-10-30-main-INFO -com.cg.BankingSystem.dao.AdminDaoImpl:AdminDao.createNewAccount(): User details for CC123 entered in account_master table.
2019-10-30-main-INFO -com.cg.BankingSystem.dao.AdminDaoImpl:AdminDao.createNewAccount(): New account added to customer table for creating new account.
2019-10-30-main-INFO -com.cg.BankingSystem.dao.AdminDaoImpl:AdminDao.createNewAccount(): User details for CC123 entered in customer table.
2019-10-30-main-INFO -com.cg.BankingSystem.dao.AdminDaoImpl:AdminDao.createNewAccount(): New account added to user_table for creating new account.
2019-10-30-main-INFO -com.cg.BankingSystem.dao.AdminDaoImpl:AdminDao.createNewAccount(): User details for CC123 entered in user_table.
2019-10-30-main-INFO -com.cg.BankingSystem.dao.AdminDaoImpl:Admin logged in successfully at: 2019-10-30T16:56:55.925
2019-10-30-main-INFO -com.cg.BankingSystem.dao.AdminDaoImpl:Create new account method initiated in DAO Layer.
2019-10-30-main-INFO -com.cg.BankingSystem.dao.AdminDaoImpl:AdminDao.createNewAccount(): New account added to account_master table for creating new account.
2019-10-30-main-INFO -com.cg.BankingSystem.dao.AdminDaoImpl:AdminDao.createNewAccount(): User details for CC124 entered in account_master table.
2019-10-30-main-INFO -com.cg.BankingSystem.dao.AdminDaoImpl:AdminDao.createNewAccount(): New account added to customer table for creating new account.
2019-10-30-main-INFO -com.cg.BankingSystem.dao.AdminDaoImpl:AdminDao.createNewAccount(): User details for CC124 entered in customer table.
2019-10-30-main-INFO -com.cg.BankingSystem.dao.AdminDaoImpl:AdminDao.createNewAccount(): New account added to user_table for creating new account.
2019-10-30-main-INFO -com.cg.BankingSystem.dao.AdminDaoImpl:AdminDao.createNewAccount(): User details for CC124 entered in user_table.
2019-10-30-main-INFO -com.cg.BankingSystem.dao.CustomerDaoImpl:Customer with user ID: CC123 logged in at: 2019-10-30T17:07:59.896
2019-10-30-main-INFO -com.cg.BankingSystem.dao.CustomerDaoImpl:Customer with user ID: CC123 logged in at: 2019-10-30T17:08:50.665
2019-10-30-main-INFO -com.cg.BankingSystem.dao.CustomerDaoImpl:Customer with account_id: 10 updated address successfully.
2019-10-30-main-INFO -com.cg.BankingSystem.dao.CustomerDaoImpl:Customer with user ID: CC123 logged in at: 2019-10-30T17:11:47.185
2019-10-30-main-INFO -com.cg.BankingSystem.dao.CustomerDaoImpl:Customer with account_id: 10 updated address successfully.
2019-10-30-main-INFO -com.cg.BankingSystem.dao.CustomerDaoImpl:Customer with user ID: CC123 logged in at: 2019-10-30T17:38:35.598
2019-10-30-main-INFO -com.cg.BankingSystem.dao.CustomerDaoImpl:CustomerDao.addNewBeneficiary(): Successfully added beneficiary to beneficiary_details table in database, for: 10
2019-10-30-main-INFO -com.cg.BankingSystem.dao.CustomerDaoImpl:CustomerDao.transferFund(): 100.0 debited from: 10. Attempting crediting into: 11
2019-10-30-main-ERROR-com.cg.BankingSystem.dao.CustomerDaoImpl:InternalServerException thrown in CustomerDao.transferFund() method with cause: ORA-02289: sequence does not exist

2019-10-30-main-INFO -com.cg.BankingSystem.dao.CustomerDaoImpl:CustomerDao.transferFund(): 100.0 debited from: 10. Attempting crediting into: 11
2019-10-30-main-INFO -com.cg.BankingSystem.dao.CustomerDaoImpl:CustomerDao.transferFund(): Transaction for amount: 100.0 from: 10 to: 11 completed successfully at: 2019-10-30T17:41:38.839
